FROM java:8
MAINTAINER xiepf "xiepf.sky@gmail.com"
ENV APP_ROOT "/app"
ADD 1.0.1-SNAPSHOT $APP_ROOT/app.jar
WORKDIR $APP_ROOT
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom"]
CMD ["-jar", "app.jar"]
EXPOSE 9090